# (From horsi-vst3's cmake/HorsiEmbed.cmake, renamed.)
# Embeds binary files into a generated C++ source as byte arrays.
#
#   underheard_embed_files(<out_cpp> <namespace> <array_name> FILES f1 f2 ...)
#
# Generates:
#   namespace <ns> {
#     struct EmbeddedFile { const char* name; const unsigned char* data; size_t size; };
#     extern const EmbeddedFile <array_name>[];   // in file order
#     extern const int <array_name>Count;
#   }
# The declaration lives in the consuming code; this only writes the definitions.
# Runs at configure time and only rewrites the output when its content changes.

function(underheard_embed_files out_cpp ns array_name)
  cmake_parse_arguments(ARG "" "" "FILES" ${ARGN})

  set(body "// Generated by cmake/UnderheardEmbed.cmake. Do not edit.\n")
  string(APPEND body "#include <cstddef>\n\nnamespace ${ns}\n{\n")
  string(APPEND body "struct EmbeddedFile { const char* name; const unsigned char* data; size_t size; };\n\n")

  set(table "")
  set(idx 0)
  foreach(path IN LISTS ARG_FILES)
    get_filename_component(fname "${path}" NAME)
    file(READ "${path}" hex HEX)
    string(LENGTH "${hex}" hexlen)
    math(EXPR nbytes "${hexlen} / 2")
    # 32 bytes per line keeps the generated source readable by editors
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){32})" "\\1\n" bytes "${bytes}")
    string(APPEND body "static const unsigned char kEmbed${idx}[${nbytes}] = {\n${bytes}\n};\n\n")
    string(APPEND table "  {\"${fname}\", kEmbed${idx}, ${nbytes}},\n")
    math(EXPR idx "${idx} + 1")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
  endforeach()

  string(APPEND body "extern const EmbeddedFile ${array_name}[];\n")
  string(APPEND body "extern const int ${array_name}Count;\n")
  string(APPEND body "const EmbeddedFile ${array_name}[] = {\n${table}};\n")
  string(APPEND body "const int ${array_name}Count = ${idx};\n\n} // namespace ${ns}\n")

  file(CONFIGURE OUTPUT "${out_cpp}" CONTENT "${body}" @ONLY)
endfunction()
